version: '3'

services:
  hub:
    image: selenium/hub:3.12.0-boron
    expose:
      - 4444
    networks:
      - selenium-grid

  chrome:
    image: isortegah/node-chrome
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    ports:
      - 5900:5900
    depends_on:
      - hub
    networks:
      - selenium-grid

networks:
  selenium-grid:
    driver: bridge