seleniumhub:
  image: selenium/hub:latest
  ports:
    - 4444:4444
chromenode:
  image: selenium/node-chrome:latest
  links:
    - seleniumhub:hub
  ports:
    - "5900:5900"
chromenode1:
  image: selenium/node-chrome:latest
  links:
    - seleniumhub:hub
  ports:
    - "5901:5900"